import {describe,expect,it,vi} from "vitest";
import {DemoContentPackageProvider} from "./demo-provider";
import {generateContentPackage,type ContentPackageProvider,type ContentPackageRepository} from "./generation";
const sourceId="71000000-4000-4000-8000-000000000001";
const input={workspaceId:"71000000-1000-4000-8000-000000000001",ideaId:"71000000-5000-4000-8000-000000000001",ideaTitle:"Evidence-led growth",ideaPremise:"Use verified research to make a practical video.",requestedBy:"71000000-0000-4000-8000-000000000001",idempotencyKey:"package-one",modelVersion:"demo-v1",promptVersion:"package-v1",evidence:[{id:sourceId,title:"Source",content:"Finding",url:"https://example.com/source"}]};
const valid={titles:["A valid evidence-led title"],thumbnailConcepts:[{concept:"Clear visual contrast",visualDescription:"Evidence on one side and assumptions on the other.",overlayText:"THE EVIDENCE"}],hooks:["The evidence changes how we should approach this problem."],outline:[{section:"Problem",purpose:"Frame the viewer problem clearly.",keyPoints:["Audience need"]},{section:"Evidence",purpose:"Explain what the source supports.",keyPoints:["Verified finding"]},{section:"Action",purpose:"Give the viewer practical next steps.",keyPoints:["Apply carefully"]}],script:"This is a sufficiently long script that introduces the problem, explains the cited evidence without overstating it, translates the finding into practical steps for the viewer, and closes with a careful evidence-backed takeaway.",citations:[sourceId]};
const repo=():ContentPackageRepository=>({persist:vi.fn().mockResolvedValue({})});
describe("content package generation",()=>{
  it("validates and persists exactly one complete bounded package",async()=>{const repository=repo();await expect(generateContentPackage({generate:vi.fn().mockResolvedValue(valid)},repository,input)).resolves.toEqual(valid);expect(repository.persist).toHaveBeenCalledOnce()});
  it("rejects invented and duplicate citations before persistence",async()=>{const repository=repo();await expect(generateContentPackage({generate:vi.fn().mockResolvedValue({...valid,citations:["72000000-4000-4000-8000-000000000002"]})},repository,input)).rejects.toMatchObject({code:"invalid_package_evidence"});await expect(generateContentPackage({generate:vi.fn().mockResolvedValue({...valid,citations:[sourceId,sourceId]})},repository,input)).rejects.toMatchObject({code:"invalid_package_evidence"});expect(repository.persist).not.toHaveBeenCalled()});
  it("rejects malformed or oversized model output",async()=>{const repository=repo();await expect(generateContentPackage({generate:vi.fn().mockResolvedValue({...valid,titles:[]})},repository,input)).rejects.toMatchObject({code:"invalid_package_output"});expect(repository.persist).not.toHaveBeenCalled()});
  it("enforces a timeout even when the provider ignores cancellation",async()=>{const provider:ContentPackageProvider={generate:()=>new Promise(()=>undefined)};await expect(generateContentPackage(provider,repo(),input,100)).rejects.toMatchObject({code:"package_generation_timeout"})});
  it("keeps demo output deterministic and directly cited",async()=>{const provider=new DemoContentPackageProvider();const first=await provider.generate(input,new AbortController().signal);const second=await provider.generate(input,new AbortController().signal);expect(first).toEqual(second);expect(first.citations).toEqual([sourceId])});
});
